export default [
    {"name":"Hidrogenio","symbol":"H","atomicNumber":1,"weight":1,"familia":"1(1A)","periodo":"1","pontoEbulicao":"20,28 K","pontoFusao":"14,025 K","classificacao":"nao-metais"},
    {"name":"Helio","symbol":"He","atomicNumber":2,"weight":4,"familia":"18(8A)","periodo":"1","pontoEbulicao":"-268,94°C,","pontoFusao":"-272,1°C","classificacao":"gases-nobres"},
    {"name":"Litio","symbol":"Li","atomicNumber":3,"weight":6.94,"familia":"1(1A)","periodo":"2","pontoEbulicao":"1342 °C","pontoFusao":"180,5 °C","classificacao":"metais-alcalinos"},
    {"name":"Berilio","symbol":"Be","atomicNumber":4,"weight":9.01,"familia":"2(2A)","periodo":"2","pontoEbulicao":"2469 °C","pontoFusao":"1287 °C","classificacao":"metais-alcalinos-terra"},
    {"name":"Boro","symbol":"B","atomicNumber":5,"weight":10.81,"familia":"13(3A)","periodo":"2","pontoEbulicao":"4000°C","pontoFusao":"2075 °C","classificacao":"semi-metais"},
    {"name":"Carbono","symbol":"C","atomicNumber":6,"weight":12.01,"familia":"14(4A)","periodo":"2","pontoEbulicao":"4287ºC","pontoFusao":"3550 ºC","classificacao":"nao-metais"},
    {"name":"Nitrogenio","symbol":"N","atomicNumber":7, "weight":14,"familia":"15(5A)","periodo":"2","pontoEbulicao":"-198,79 °C","pontoFusao":"-210,00 °C","classificacao":"nao-metais"},
    {"name":"Oxigenio","symbol":"O","atomicNumber":8, "weight":15.99,"familia":"16(6A)","periodo":"2","pontoEbulicao":"-182,8 °C","pontoFusao":"- 218,4 °C","classificacao":"nao-metais"},
    {"name":"Fluor","symbol":"F","atomicNumber":9, "weight":18.99,"familia":"17(7A)","periodo":"2","pontoEbulicao":"-188,12 °C","pontoFusao":"-219,62 °C","classificacao":"halogenios"},
    {"name":"Neonio","symbol":"Ne","atomicNumber":10, "weight":20.17,"familia":"18(8A)","periodo":"2","pontoEbulicao":"-246,08 °C","pontoFusao":"–248,6 °C","classificacao":"gases-nobres"},
    {"name":"Sodio","symbol":"Na","atomicNumber":11, "weight":22.98,"familia":"1(1A)","periodo":"3","pontoEbulicao":"883 °C","pontoFusao":"97,80 °C","classificacao":"metais-alcalinos"},
    {"name":"Magnesio","symbol":"Mg","atomicNumber":12, "weight":24.30,"familia":"2(2A)","periodo":"3","pontoEbulicao":"1090 °C","pontoFusao":"650 °C","classificacao":"metais-alcalinos-terra"},
    {"name":"Aluminio","symbol":"Al","atomicNumber":13, "weight":26.98,"familia":"13(3A)","periodo":"3","pontoEbulicao":"2519 °C","pontoFusao":"660,323 °C","classificacao":"metais-representativos"},
    {"name":"Silicio","symbol":"Si","atomicNumber":14,"weight":20.17,"familia":"14(4A)","periodo":"3","pontoEbulicao":"3265 °C","pontoFusao":"1414 °C","classificacao":"semi-metais"},
    {"name":"Fosforo","symbol":"P","atomicNumber":15, "weight":22.98,"familia":"15(5A)","periodo":"3","pontoEbulicao":"280,5 °C","pontoFusao":"44,15 °C","classificacao":"nao-metais"},
    {"name":"Enxofre","symbol":"S","atomicNumber":16, "weight":24.30,"familia":"16(6A)","periodo":"3","pontoEbulicao":"444,60 °C","pontoFusao":"115,21 °C","classificacao":"nao-metais"},
    {"name":"Cloro","symbol":"Cl","atomicNumber":17,"weight": 35.45,"familia":"17(7A)","periodo":"3","pontoEbulicao":"-34,04 °C","pontoFusao":"-101,5 °C","classificacao":"halogenios"},
    {"name":"Argonio","symbol":"Ar","atomicNumber":18, "weight":39.94,"familia":"18(8A)","periodo":"3","pontoEbulicao":"-185,84ºC","pontoFusao":"-189,34ºC","classificacao":"gases-nobres"},
    {"name":"Potassio","symbol":"K","atomicNumber":19, "weight":39.09,"familia":"1(1A)","periodo":"4","pontoEbulicao":"774,0 ° C","pontoFusao":"63,65 ° C","classificacao":"metais-alcalinos"},
    {"name":"Calcio","symbol":"Ca","atomicNumber":20,"weight": 40.07,"familia":"2(2A)","periodo":"4","pontoEbulicao":"1484 °C","pontoFusao":"842 °C","classificacao":"metais-alcalinos-terra"},
    {"name":"Escandio","symbol":"Sc","atomicNumber":21, "weight":44.95,"familia":"3(3B)","periodo":"4","pontoEbulicao":"2836 °C","pontoFusao":"1541 °C","classificacao":"metais-transicao"},
    {"name":"Titanio","symbol":"Ti","atomicNumber":22, "weight":47.86,"familia":"4(4B)","periodo":"4","pontoEbulicao":"3287 °C","pontoFusao":"1668 °C","classificacao":"metais-transicao"},
    {"name":"Vanadio","symbol":"V","atomicNumber":23, "weight":50.94,"familia":"5(5B)","periodo":"4","pontoEbulicao":"3407°C","pontoFusao":"1910°C","classificacao":"metais-transicao"},
    {"name":"Cromo","symbol":"Cr","atomicNumber":24,"weight":51.99,"familia":"6(6B)","periodo":"4","pontoEbulicao":"2671 °C","pontoFusao":"1907 °C","classificacao":"metais-transicao"},
    {"name":"Manganes","symbol":"Mn","atomicNumber":25, "weight":54.93,"familia":"7(7B)","periodo":"4","pontoEbulicao":"2061 °C","pontoFusao":"1246 °C","classificacao":"metais-transicao"},
    {"name":"Ferro","symbol":"Fe","atomicNumber":26, "weight":55.84,"familia":"8(8B)","periodo":"4","pontoEbulicao":"3000°C","pontoFusao":"1535 °C","classificacao":"metais-transicao"},
    {"name":"Cobalto","symbol":"Co","atomicNumber":27, "weight":58.93,"familia":"9(8B)","periodo":"4","pontoEbulicao":"2927 °C","pontoFusao":"1495 °C","classificacao":"metais-transicao"},
    {"name":"Niquel","symbol":"Ni","atomicNumber":28, "weight":58.69,"familia":"10(8B)","periodo":"4","pontoEbulicao":"2913 °C","pontoFusao":"1455 °C","classificacao":"metais-transicao"},
    {"name":"Cobre","symbol":"Cu","atomicNumber":29, "weight":63.54,"familia":"11(1B)","periodo":"4","pontoEbulicao":"2562 °C","pontoFusao":"1084,62 °C","classificacao":"metais-transicao"},
    {"name":"Zinco","symbol":"Zn","atomicNumber":30, "weight":65.40,"familia":"12(2B)","periodo":"4","pontoEbulicao":"907 °C","pontoFusao":"419.53 °C","classificacao":"metais-transicao"},
    {"name":"Galio","symbol":"Ga","atomicNumber":31, "weight":69.72,"familia":"13(3A)","periodo":"4","pontoEbulicao":"2204 °C","pontoFusao":"29,76 °C","classificacao":"metais-representativos"},
    {"name":"Germanio","symbol":"Ge","atomicNumber":32, "weight":72.64,"familia":"14(4A)","periodo":"4","pontoEbulicao":"2833 °C","pontoFusao":"938,25 °C","classificacao":"semi-metais"},
    {"name":"Arsenio","symbol":"As","atomicNumber":33,"weight":74.92,"familia":"15(5A)","periodo":"4","pontoEbulicao":"614 °C","pontoFusao":"862 °C","classificacao":"semi-metais"},
    {"name":"Selenio","symbol":"Se","atomicNumber":34,"weight":78.96,"familia":"16(6A)","periodo":"4","pontoEbulicao":"685 °C","pontoFusao":"221 °C","classificacao":"nao-metais"},
    {"name":"Bromo","symbol":"Br","atomicNumber":35,"weight":79.90,"familia":"17(7A)","periodo":"4","pontoEbulicao":"58,8 °C","pontoFusao":"-7,2 °C","classificacao":"halogenios"},
    {"name":"Criptonio","symbol":"Kr", "atomicNumber":36,"weight":83.79,"familia":"18(8A)","periodo":"4","pontoEbulicao":"152,3 °C","pontoFusao":"156,6 °C","classificacao":"gases-nobres"},
    {"name":"Rubidio","symbol":"Rb", "atomicNumber":37,"weight":85.46,"familia":"1(1A)","periodo":"5","pontoEbulicao":"688 °C","pontoFusao":"39,31 °C","classificacao":"metais-alcalinos"},
    {"name":"Estroncio","symbol":"Sr","atomicNumber":38,"weight":87.62,"familia":"2(2A)","periodo":"5","pontoEbulicao":"1382 °C","pontoFusao":"777 °C","classificacao":"metais-alcalinos-terra"},
    {"name":"Itrio","symbol":"Y", "atomicNumber":39,"weight":88.90,"familia":"3(3B)","periodo":"5","pontoEbulicao":"3345 °C","pontoFusao":"1522 °C","classificacao":"metais-transicao"},
    {"name":"Zirconio","symbol":"Zr", "atomicNumber":40,"weight":91.22,"familia":"4(4B)","periodo":"5","pontoEbulicao":"4409 °C","pontoFusao":"1855 °C","classificacao":"metais-transicao"},
    {"name":"Niobio","symbol":"Nb", "atomicNumber":41,"weight":92.90,"familia":"5(5B)","periodo":"5","pontoEbulicao":"4744 °C","pontoFusao":"2477 °C","classificacao":"metais-transicao"},
    {"name":"Molibidenio","symbol":"Mo","atomicNumber":42,"weight":95.94,"familia":"6(6B)","periodo":"5","pontoEbulicao":"4639 °C","pontoFusao":"2623 °C","classificacao":"metais-transicao"},
    {"name":"Tecnecio","symbol":"Tc","atomicNumber":43,"weight":98.00,"familia":"7(7B)","periodo":"5","pontoEbulicao":"4265 °C","pontoFusao":"2157 °C","classificacao":"metais-transicao"},
    {"name":"Rutenio","symbol":"Ru","atomicNumber":44,"weight":101.07,"familia":"8(8B)","periodo":"5","pontoEbulicao":"4150 °C","pontoFusao":"2334 °C","classificacao":"metais-transicao"},
    {"name":"Rodio","symbol":"Rh","atomicNumber":45,"weight":102.90,"familia":"9(8B)","periodo":"5","pontoEbulicao":"3695 °C","pontoFusao":"1964 °C","classificacao":"metais-transicao"},
    {"name":"Paladio","symbol":"Pd","atomicNumber":46,"weight":106.42,"familia":"10(8B)","periodo":"5","pontoEbulicao":"3236 °C","pontoFusao":"1554,9 °C","classificacao":"metais-transicao"},
    {"name":"Prata","symbol":"Ag", "atomicNumber":47,"weight":107.86,"familia":"11(1B)","periodo":"5","pontoEbulicao":"2162 °C","pontoFusao":"961,78 °C","classificacao":"metais-transicao"},
    {"name":"Cadmio","symbol":"Cd","atomicNumber":48,"weight":112.41,"familia":"12(2B)","periodo":"5","pontoEbulicao":"767 °C","pontoFusao":"321,07 °C","classificacao":"metais-transicao"},
    {"name":"Indio","symbol":"In", "atomicNumber":49,"weight":114.81,"familia":"13(3A)","periodo":"5","pontoEbulicao":"2072 °C","pontoFusao":"156,60 °C","classificacao":"metais-representativos"},
    {"name":"Estanho","symbol":"Sn","atomicNumber":50,"weight":118.71,"familia":"14(4A)","periodo":"5","pontoEbulicao":"2602 °C","pontoFusao":"231,93 °C","classificacao":"metais-representativos"},
    {"name":"Antimonio","symbol":"Sb","atomicNumber":51,"weight":121.76,"familia":"15(5A)","periodo":"5","pontoEbulicao":"1587 °C","pontoFusao":"630,63 °C","classificacao":"semi-metais"},
    {"name":"Telurio","symbol":"Te","atomicNumber":52,"weight":128.60,"familia":"16(6A)","periodo":"5","pontoEbulicao":"988 °C","pontoFusao":"449,51 °C","classificacao":"semi-metais"},
    {"name":"Iodo","symbol":"I","atomicNumber":53,"weight":126.90,"familia":"17(7A)","periodo":"5","pontoEbulicao":"184,4 °C","pontoFusao":"113,7 °C","classificacao":"halogenios"},
    {"name":"Xenonio","symbol":"Xe","atomicNumber":54,"weight":131.29,"familia":"18(8A)","periodo":"5","pontoEbulicao":"-108,12 °C","pontoFusao":"-111,79 °C","classificacao":"gases-nobres"},
    {"name":"Cesio","symbol":"Cs", "atomicNumber":55,"weight":132.90,"familia":"1(1A)","periodo":"6","pontoEbulicao":"671 °C","pontoFusao":"28,44 °C","classificacao":"metais-alcalinos"},
    {"name":"Bario","symbol":"Ba", "atomicNumber":56,"weight":137.32,"familia":"2(2A)","periodo":"6","pontoEbulicao":"1897 °C","pontoFusao":"727 °C","classificacao":"metais-alcalinos-terra"},
    {"name":"Lantanio","symbol":"La","atomicNumber":57,"weight":138.90,"familia":"","periodo":"6","pontoEbulicao":"3460ºC","pontoFusao":"920ºC","classificacao":"lantanideos"},
    {"name":"Cerio","symbol":"Ce", "atomicNumber":58,"weight":140.11,"familia":"","periodo":"6","pontoEbulicao":"3424 °C","pontoFusao":"798 °C","classificacao":"lantanideos"},
    {"name":"Praseodimio","symbol":"Pr", "atomicNumber":59,"weight":140.90,"familia":"","periodo":"6","pontoEbulicao":"3520 °C","pontoFusao":"931 °C",  "classificacao":"lantanideos"},
    {"name":"Neodimio","symbol":"Nd","atomicNumber":60,"weight":144.24,"familia":"","periodo":"6","pontoEbulicao":"3074 °C","pontoFusao":"1021 °C","classificacao":"lantanideos"},
    {"name":"Promecio","symbol":"Pm","atomicNumber":61,"weight":0.00,"familia":"","periodo":"6","pontoEbulicao":"3000 °C","pontoFusao":"1042 °C","classificacao":"lantanideos"},
    {"name":"Samario","symbol":"Sm", "atomicNumber":62,"weight":150.36,"familia":"","periodo":"6","pontoEbulicao":"1794 °C","pontoFusao":"1074 °C","classificacao":"lantanideos"},
    {"name":"Europio","symbol":"Eu", "atomicNumber":63,"weight":151.96,"familia":"","periodo":"6","pontoEbulicao":"1596 °C","pontoFusao":"822 °C","classificacao":"lantanideos"},
    {"name":"Gadolinio","symbol":"Gd","atomicNumber":64, "weight":157.25,"familia":"","periodo":"6","pontoEbulicao":"3273 °C","pontoFusao":"1313 °C","classificacao":"lantanideos"},
    {"name":"Terbio","symbol":"Tb","atomicNumber":65,"weight":158.92,"familia":"","periodo":"6","pontoEbulicao":"3230 °C","pontoFusao":"1356 °C","classificacao":"lantanideos"},
    {"name":"Disprosio","symbol":"Dy","atomicNumber":66,"weight":162.50,"familia":"","periodo":"6","pontoEbulicao":"2567 °C","pontoFusao":"1412 °C","classificacao":"lantanideos"},
    {"name":"Holmio","symbol":"Ho","atomicNumber":67, "weight":164.93,"familia":"","periodo":"6","pontoEbulicao":"2700 °C","pontoFusao":"1474 °C","classificacao":"lantanideos"},
    {"name":"Erbio","symbol":"Er","atomicNumber":68, "weight":167.25,"familia":"","periodo":"6","pontoEbulicao":"1529 °C","pontoFusao":"1529 ° C","classificacao":"lantanideos"},
    {"name":"Tulio","symbol":"Tm","atomicNumber":69, "weight":168.93,"familia":"","periodo":"6","pontoEbulicao":"1950 °C","pontoFusao":"1545 °C","classificacao":"lantanideos"},
    {"name":"Iterbio","symbol":"Yb","atomicNumber":70,"weight":173.04,"familia":"","periodo":"6","pontoEbulicao":"1196 °C","pontoFusao":"819 °C","classificacao":"lantanideos"},
    {"name":"Lutecio","symbol":"Lu","atomicNumber":71,"weight":174.96,"familia":"","periodo":"6","pontoEbulicao":"3402 °C","pontoFusao":"1663 °C","classificacao":"lantanideos"},
    {"name":"Hafnio","symbol":"Hf", "atomicNumber":72,"weight":178.49,"familia":"4(4B)","periodo":"6","pontoEbulicao":"4603 °C","pontoFusao":"2233 °C","classificacao":"metais-transicao"},
    {"name":"Tanlalo","symbol":"Ta","atomicNumber":73,"weight":180.94,"familia":"5(5B)","periodo":"6","pontoEbulicao":"5458 °C","pontoFusao":"3017 °C","classificacao":"metais-transicao"},
    {"name":"Tungstenio","symbol":"W","atomicNumber":74,"weight":183.84,"familia":"6(6B)","periodo":"6","pontoEbulicao":"5555 °C","pontoFusao":"3422 °C","classificacao":"metais-transicao"},
    {"name":"Renio","symbol":"Re", "atomicNumber":75,"weight":186.20,"familia":"7(7B)","periodo":"6","pontoEbulicao":"5596 °C","pontoFusao":"3186 °C","classificacao":"metais-transicao"},
    {"name":"Osmio","symbol":"Os","atomicNumber":76,"weight":190.23,"familia":"8(8B)","periodo":"6","pontoEbulicao":"5012 °C","pontoFusao":"3033 °C","classificacao":"metais-transicao"},
    {"name":"Iridio","symbol":"Ir","atomicNumber":77,"weight":192.21,"familia":"9(8B)","periodo":"6","pontoEbulicao":"4428 °C","pontoFusao":"1964 °C","classificacao":"metais-transicao"},
    {"name":"Platina","symbol":"Pt","atomicNumber":78,"weight":195.08,"familia":"10(8B)","periodo":"6","pontoEbulicao":"3825 °C","pontoFusao":"1768,4 °C","classificacao":"metais-transicao"},
    {"name":"Ouro","symbol":"Au", "atomicNumber":79,"weight":196.96,"familia":"11(1B)","periodo":"6","pontoEbulicao":"2856 °C","pontoFusao":"1064,18 °C","classificacao":"metais-transicao"},
    {"name":"Mercurio","symbol":"Hg", "atomicNumber":80,"weight":200.59,"familia":"12(2B)","periodo":"6","pontoEbulicao":"356,73 °C","pontoFusao":"-38,83 °C","classificacao":"metais-transicao"},
    {"name":"Talio","symbol":"Tl", "atomicNumber":81,"weight":204.38,"familia":"13(3A)","periodo":"6","pontoEbulicao":"1473 °C","pontoFusao":"304 °C","classificacao":"metais-representativos"},
    {"name":"Chumbo","symbol":"Pb", "atomicNumber":82,"weight":207.20,"familia":"14(4A)","periodo":"6","pontoEbulicao":"1749 °C","pontoFusao":"327.46 °C","classificacao":"metais-representativos"},
    {"name":"Bismuto","symbol":"Bi","atomicNumber":83,"weight":208.98,"familia":"15(5A)","periodo":"6","pontoEbulicao":"1564 °C","pontoFusao":"271,4 °C","classificacao":"metais-representativos"},
    {"name":"Polonio","symbol":"Po","atomicNumber":84,"weight":0,"familia":"16(6A)","periodo":"6","pontoEbulicao":"962 °C","pontoFusao":"254 °C","classificacao":"semi-metais"},
    {"name":"Astato","symbol":"At", "atomicNumber":85,"weight":0,"familia":"17(7A)","periodo":"6","pontoEbulicao":"302 °C ","pontoFusao":"Sem dados","classificacao":"halogenios"},
    {"name":"Radonio","symbol":"Rn","atomicNumber":86,"weight":0,"familia":"18(8A)","periodo":"6","pontoEbulicao":"-61,7 °C","pontoFusao":"-71 °C","classificacao":"gases-nobres"},
    {"name":"Francio","symbol":"Fr","atomicNumber":87,"weight":0,"familia":"1(1A)","periodo":"7","pontoEbulicao":"677 °C","pontoFusao":"27 °C","classificacao":"metais-alcalinos"},
    {"name":"Radio","symbol":"Ra", "atomicNumber":88,"weight":0,"familia":"2(2A)","periodo":"7","pontoEbulicao":"1737 °C","pontoFusao":"700 °C","classificacao":"metais-alcalinos-terra"},
    {"name":"Actinio","symbol":"Ac", "atomicNumber":89,"weight":0,"familia":"","periodo":"7","pontoEbulicao":"3200±300 °C","pontoFusao":"1051 °C","classificacao":"actinideos"},
    {"name":"Torio","symbol":"Th","atomicNumber":90,"weight":232.03,"familia":"","periodo":"7","pontoEbulicao":"4788 °C","pontoFusao":"1750 °C","classificacao":"actinideos"},
    {"name":"Protactinio","symbol":"Pa", "atomicNumber":91,"weight":231.03,"familia":"","periodo":"7","pontoEbulicao":"4027 °C","pontoFusao":"1572 °C",  "classificacao":"actinideos"},
    {"name":"Uranio","symbol":"U", "atomicNumber":92,"weight":238.02,"familia":"","periodo":"7","pontoEbulicao":"4131 °C","pontoFusao":"1131,9 °C","classificacao":"actinideos"},
    {"name":"Neptunio","symbol":"Np","atomicNumber":93,"weight":0,"familia":"","periodo":"7","pontoEbulicao":"4000 °C","pontoFusao":"637 °C","classificacao":"actinideos"},
    {"name":"Plutonio","symbol":"Pu","atomicNumber":94,"weight":0,"familia":"","periodo":"7","pontoEbulicao":"3232 °C","pontoFusao":"638,8 °C","classificacao":"actinideos"},
    {"name":"Americio","symbol":"Am","atomicNumber":95,"weight":0,"familia":"","periodo":"7","pontoEbulicao":"2011 °C","pontoFusao":"1176 °C","classificacao":"actinideos"},
    {"name":"Curio","symbol":"Cm","atomicNumber":96,"weight":0,"familia":"","periodo":"7","pontoEbulicao":"3110 °C","pontoFusao":"1345 °C","classificacao":"actinideos"},
    {"name":"Berquelio","symbol":"Bk","atomicNumber":97,"weight":0,"familia":"","periodo":"7","pontoEbulicao":"","pontoFusao":"1323 K","classificacao":"actinideos"},
    {"name":"Californio","symbol":"Cf","atomicNumber":98,"weight":0,"familia":"","periodo":"7","pontoEbulicao":"1470 °C","pontoFusao":"900 °C","classificacao":"actinideos"},
    {"name":"Einstenio","symbol":"Es","atomicNumber":99,"weight":0,"familia":"","periodo":"7","pontoEbulicao":"","pontoFusao":"860 °C","classificacao":"actinideos"},
    {"name":"Fermio","symbol":"Fm","atomicNumber":100,"weight":0,"familia":"","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"1527 °C","classificacao":"actinideos"},
    {"name":"Mendelevio","symbol":"Md","atomicNumber":101,"weight":0,"familia":"","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"827 °C","classificacao":"actinideos"},
    {"name":"Nobelio","symbol":"No","atomicNumber":102,"weight":0,"familia":"","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"830 °C","classificacao":"actinideos"},
    {"name":"Laurencio","symbol":"Lr","atomicNumber":103,"weight":0,"familia":"","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"1600 °C","classificacao":"actinideos"},
    {"name":"Rutherfordio","symbol":"Rf","atomicNumber":104,"weight":0,"familia":"4(4B)","periodo":"7","pontoEbulicao":"5800 K","pontoFusao":"2400 K","classificacao":"metais-transicao"},
    {"name":"Dubnio","symbol":"Db","atomicNumber":105,"weight":0,"familia":"5(5B)","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"Desconhecido","classificacao":"metais-transicao"},
    {"name":"Seaborgio","symbol":"Sg","atomicNumber":106,"weight":0,"familia":"6(6B)","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"Desconhecido","classificacao":"metais-transicao"},
    {"name":"Bonrio","symbol":"Bh","atomicNumber":107,"weight":0,"familia":"7(7B)","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"Desconhecido","classificacao":"metais-transicao" },
    {"name":"Hassio","symbol":"Hs","atomicNumber":108,"weight":0,"familia":"8(8B)","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"Desconhecido","classificacao":"metais-transicao" },
    {"name":"Meitnerio","symbol":"Mt","atomicNumber":109,"weight":0,"familia":"9(8B)","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"Desconhecido","classificacao":"metais-transicao" },
    {"name":"Darmstacio","symbol":"Ds","atomicNumber":110,"weight":0,"familia":"10(8B)","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"Desconhecido","classificacao":"metais-transicao" },
    {"name":"Roentgenio","symbol":"Rg","atomicNumber":111,"weight":0,"familia":"11(1B)","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"Desconhecido","classificacao":"metais-transicao"},
    {"name":"Copernicio","symbol":"Cn","atomicNumber":112,"weight":0,"familia":"12(2B)","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"Desconhecido","classificacao":"metais-transicao"},
    {"name":"Niponio","symbol":"Nh","atomicNumber":113, "weight":0,"familia":"13(3A)","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"Desconhecido", "classificacao":"metais-representativos"},
    {"name":"Flerovio","symbol":"Fl","atomicNumber":114,"weight":0,"familia":"14(4A)","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"Desconhecido", "classificacao":"metais-representativos"},
    {"name":"Moscovio","symbol":"Ms","atomicNumber":115, "weight":0,"familia":"15(5A)","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"Desconhecido", "classificacao":"metais-representativos"},
    {"name":"Livermorio","symbol":"Lv","atomicNumber":116, "weight":0,"familia":"16(6A)","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"Desconhecido", "classificacao":"metais-representativos"},
    {"name":"Tenesso","symbol":"Ts","atomicNumber":117,"weight":0,"familia":"17(7A)","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"Desconhecido","classificacao":"halogenios"},
    {"name":"Oganesson","symbol":"Og","atomicNumber":118,"weight":0,"familia":"18(8A)","periodo":"7","pontoEbulicao":"Desconhecido","pontoFusao":"Desconhecido","classificacao":"gases-nobres"}
]
