export default [
    {"name":"Hidrogenio","symbol":"H","atomicNumber":1,"weight":1.008},
    {"name":"Helio","symbol":"He","atomicNumber":2,"weight":4.000},
    {"name":"Litio","symbol":"Li","atomicNumber":3,"weight":6.941},
    {"name":"Berilio","symbol":"Be","atomicNumber":4,"weight":9.012},
    {"name":"Boro","symbol":"B","atomicNumber":5,"weight":10.811},
    {"name":"Carbono","symbol":"C","atomicNumber":6,"weight":12.011},
    {"name":"Nitrogenio","symbol":"N","atomicNumber":7, "weight":14.001},
    {"name":"Oxigenio","symbol":"O","atomicNumber":8, "weight":15.999},
    {"name":"Fluor","symbol":"F","atomicNumber":9, "weight":18.998},
    {"name":"Neonio","symbol":"Ne","atomicNumber":10, "weight":20.179},
    {"name":"Sodio","symbol":"Na","atomicNumber":11, "weight":22.989},
    {"name":"Magnesio","symbol":"Mg","atomicNumber":12, "weight":24.305},
    {"name":"Aluminio","symbol":"Al","atomicNumber":13, "weight":26.981},
    {"name":"Silicio","symbol":"Si","atomicNumber":14,"weight":20.179},
    {"name":"Fosforo","symbol":"P","atomicNumber":15, "weight":22.989},
    {"name":"Enxofre","symbol":"S","atomicNumber":16, "weight":24.305},
    {"name":"Cloro","symbol":"Cl","atomicNumber":17,"weight": 35.453},
    {"name":"Argonio","symbol":"Ar","atomicNumber":18, "weight":39.948},
    {"name":"Potassio","symbol":"K","atomicNumber":19, "weight":39.098},
    {"name":"Calcio","symbol":"Ca","atomicNumber":20,"weight": 40.078},
    {"name":"Escandio","symbol":"Sc","atomicNumber":21, "weight":44.956},
    {"name":"Titanio","symbol":"Ti","atomicNumber":22, "weight":47.867},
    {"name":"Vanadio","symbol":"V","atomicNumber":23, "weight":50.941},
    {"name":"Cromo","symbol":"Cr","atomicNumber":24,"weight":51.996},
    {"name":"Manganes","symbol":"Mn","atomicNumber":25, "weight":54.938},
    {"name":"Ferro","symbol":"Fe","atomicNumber":26, "weight":55.845},
    {"name":"Cobalto","symbol":"Co","atomicNumber":27, "weight":58.933},
    {"name":"Niquel","symbol":"Ni","atomicNumber":28, "weight":58.693},
    {"name":"Cobre","symbol":"Cu","atomicNumber":29, "weight":63.546},
    {"name":"Zinco","symbol":"Zn","atomicNumber":30, "weight":65.409},
    {"name":"Galio","symbol":"Ga","atomicNumber":31, "weight":69.723},
    {"name":"Germanio","symbol":"Ge","atomicNumber":32, "weight":72.64},
    {"name":"Arsenio","symbol":"As","atomicNumber":33,"weight":74.921},
    {"name":"Selenio","symbol":"Se","atomicNumber":34,"weight":78.960},
    {"name":"Bromo","symbol":"Br","atomicNumber":35,"weight":79.904},
    {"name":"Criptonio","symbol":"Kr", "atomicNumber":36,"weight":83.798},
    {"name":"Rubidio","symbol":"Rb", "atomicNumber":37,"weight":85.468},
    {"name":"Estroncio","symbol":"Sr","atomicNumber":38,"weight":87.620},
    {"name":"Itrio","symbol":"Y", "atomicNumber":39,"weight":88.905},
    {"name":"Zirconio","symbol":"Zr", "atomicNumber":40,"weight":91.224},
    {"name":"Niobio","symbol":"Nb", "atomicNumber":41,"weight":92.906},
    {"name":"Molibidenio","symbol":"Mo","atomicNumber":42,"weight":95.940},
    {"name":"Tecnecio","symbol":"Tc","atomicNumber":43,"weight":98.000},
    {"name":"Rutenio","symbol":"Ru","atomicNumber":44,"weight":101.070},
    {"name":"Rodio","symbol":"Rh","atomicNumber":45,"weight":102.905},
    {"name":"Paladio","symbol":"Pd","atomicNumber":46,"weight":106.420},
    {"name":"Prata","symbol":"Ag", "atomicNumber":47,"weight":107.867},
    {"name":"Cadmio","symbol":"Cd","atomicNumber":48,"weight":112.411},
    {"name":"Indio","symbol":"In", "atomicNumber":49,"weight":114.818},
    {"name":"Estanho","symbol":"Sn","atomicNumber":50,"weight":118.710},
    {"name":"Antomonio","symbol":"Sb","atomicNumber":51,"weight":121.760},
    {"name":"Telurio","symbol":"Te","atomicNumber":52,"weight":128.600},
    {"name":"Iodo","symbol":"I","atomicNumber":53,"weight":126.904},
    {"name":"Xenonio","symbol":"Xe","atomicNumber":54,"weight":131.293},
    {"name":"Cesio","symbol":"Cs", "atomicNumber":55,"weight":132.905},
    {"name":"Bario","symbol":"Ba", "atomicNumber":56,"weight":137.327},
    {"name":"Lantanio","symbol":"La","atomicNumber":57,"weight":138.905},
    {"name":"Cerio","symbol":"Ce", "atomicNumber":58,"weight":140.116},
    {"name":"Praseodimio","symbol":"Pr", "atomicNumber":59,"weight":140.908},
    {"name":"Neodimio","symbol":"Nd","atomicNumber":60,"weight":144.242},
    {"name":"Promecio","symbol":"Pm","atomicNumber":61,"weight":0.000},
    {"name":"Samario","symbol":"Sm", "atomicNumber":62,"weight":150.360},
    {"name":"Europio","symbol":"Eu", "atomicNumber":63,"weight":151.964},
    {"name":"Gadolinio","symbol":"Gd","atomicNumber":64, "weight":157.250},
    {"name":"Terbio","symbol":"Tb","atomicNumber":65,"weight":158.925},
    {"name":"Disprosio","symbol":"Dy","atomicNumber":66,"weight":162.500},
    {"name":"Holmio","symbol":"Ho","atomicNumber":67, "weight":164.930},
    {"name":"Erbio","symbol":"Er","atomicNumber":68, "weight":167.259},
    {"name":"Tulio","symbol":"Tm","atomicNumber":69, "weight":168.934},
    {"name":"Iterbio","symbol":"Yb","atomicNumber":70,"weight":173.040},
    {"name":"Lutecio","symbol":"Lu","atomicNumber":71,"weight":174.967},
    {"name":"Hafnio","symbol":"Hf", "atomicNumber":72,"weight":178.490},
    {"name":"Tanlalo","symbol":"Ta","atomicNumber":73,"weight":180.948},
    {"name":"Tungstenio","symbol":"W","atomicNumber":74,"weight":183.840},
    {"name":"Renio","symbol":"Re", "atomicNumber":75,"weight":186.207},
    {"name":"Osmio","symbol":"Os","atomicNumber":76,"weight":190.23},
    {"name":"Iridio","symbol":"Ir","atomicNumber":77,"weight":192.217},
    {"name":"Platina","symbol":"Pt","atomicNumber":78,"weight":195.084},
    {"name":"Ouro","symbol":"Au", "atomicNumber":79,"weight":196.966},
    {"name":"Mercurio","symbol":"Hg", "atomicNumber":80,"weight":200.590},
    {"name":"Talio","symbol":"Tl", "atomicNumber":81,"weight":204.383},
    {"name":"Chumbo","symbol":"Cu", "atomicNumber":82,"weight":207.200},
    {"name":"Bismuto","symbol":"Bi","atomicNumber":83,"weight":208.980},
    {"name":"Polonio","symbol":"Po","atomicNumber":84,"weight":0},
    {"name":"Astato","symbol":"At", "atomicNumber":85,"weight":0},
    {"name":"Radonio","symbol":"Rn","atomicNumber":86,"weight":0},
    {"name":"Francio","symbol":"Fr","atomicNumber":87,"weight":0},
    {"name":"Radio","symbol":"Ra", "atomicNumber":88,"weight":0},
    {"name":"Actinio","symbol":"Ac", "atomicNumber":89,"weight":0},
    {"name":"Torio","symbol":"Th","atomicNumber":90,"weight":232.038},
    {"name":"Protactinio","symbol":"Pa", "atomicNumber":91,"weight":231.035},
    {"name":"Uranio","symbol":"U", "atomicNumber":92,"weight":238.029},
    {"name":"Neptunio","symbol":"Np","atomicNumber":93,"weight":0},
    {"name":"Plutonio","symbol":"Pu","atomicNumber":94,"weight":0},
    {"name":"Americio","symbol":"Am","atomicNumber":95,"weight":0},
    {"name":"Curio","symbol":"Cm","atomicNumber":96,"weight":0},
    {"name":"Berquelio","symbol":"Bk","atomicNumber":97,"weight":0},
    {"name":"Californio","symbol":"Cf","atomicNumber":98,"weight":0},
    {"name":"Einstenio","symbol":"Es","atomicNumber":99,"weight":0},
    {"name":"Fermio","symbol":"Fm","atomicNumber":100,"weight":0},  
    {"name":"Mendelevio","symbol":"Md","atomicNumber":101,"weight":0},
    {"name":"Nobelio","symbol":"No","atomicNumber":102,"weight":0},
    {"name":"Laurencio","symbol":"Lr","atomicNumber":103,"weight":0},
    {"name":"Rutherfordio","symbol":"Rf","atomicNumber":104,"weight":0},
    {"name":"Dubnio","symbol":"Db","atomicNumber":105,"weight":0},
    {"name":"Seaborgio","symbol":"Sg","atomicNumber":106,"weight":0},
    {"name":"Bonrio","symbol":"Bh","atomicNumber":107,"weight":0},
    {"name":"Hassio","symbol":"Hs","atomicNumber":108,"weight":0},
    {"name":"Meitnerio","symbol":"Mt","atomicNumber":109,"weight":0},
    {"name":"Darmstacio","symbol":"Ds","atomicNumber":110,"weight":0},
    {"name":"Roentgenio","symbol":"Rg","atomicNumber":111,"weight":0},
    {"name":"Copernicio","symbol":"Cn","atomicNumber":112,"weight":0},
    {"name":"Niponio","symbol":"Nh","atomicNumber":113, "weight":0},
    {"name":"Flerovio","symbol":"Fl","atomicNumber":114,"weight":0},
    {"name":"Moscovio","symbol":"Ms","atomicNumber":115, "weight":0},
    {"name":"Livermorio","symbol":"Lv","atomicNumber":116, "weight":0},
    {"name":"Tenesso","symbol":"Ts","atomicNumber":117,"weight":0},
    {"name":"Oganesson","symbol":"Og","atomicNumber":118,"weight":0}
]
